// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.DatePicker_ValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.SerializedMetadata.SaveAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.UpdatePagingAwait~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.btnAutoIncrement_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.btnNextPage_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.btnPreviousPage_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.btnRefresh_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.btnResetDates_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.CreateControlPanel(DocumentScanner.UserControls.BatchPageProcessing.RowData)~System.Windows.Forms.Panel")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.IncrementAndSave(DocumentScanner.UserControls.BatchPageProcessing.RowData,System.Func{System.DateTime,System.DateTime})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.PersistPageSkipAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.PicDoc_DoubleClick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.ResetPaging~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.SaveAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.SetPageAsync(System.Int32)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.SetTrash(DocumentScanner.UserControls.BatchPageProcessing.RowData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.FileExtensions.ConfirmOverwrite(System.Windows.Forms.SaveFileDialog,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.FileExtensions.RecursiveDeleteHelper(System.IO.DirectoryInfo,System.Collections.Generic.List{System.Exception})")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.FileExtensions.SafeDelete(System.IO.FileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.FileExtensions.TryDelete(System.IO.DirectoryInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.ItextPdfMerger.Merge(System.Collections.Generic.IEnumerable{DocumentScanner.NapsOptions.InputFile},System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.GetRowImage(DocumentScanner.UserControls.BatchPageProcessing.RowData)~System.Drawing.Image")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchPageProcessing.SaveAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchScan.btnClearLogFile_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.BatchScan.Log(System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentScanner.UserControls.MergeScansControl.Parse")]
